<?php

namespace Database\Seeders;

use App\Models\Medication;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MedicationSeeder extends Seeder
{
    public function run(): void
    {
        $medications = [
            [
                'active_principle' => 'Amoxicilina',
                'concentration' => '500mg',
                'presentation' => 'CAPSULA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Amoxil',
                'requires_prescription' => true,
                'contraindications' => 'Hipersensibilidad a penicilinas y cefalosporinas.',
            ],
            [
                'active_principle' => 'Ibuprofeno',
                'concentration' => '400mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Advil',
                'requires_prescription' => false,
                'contraindications' => 'Úlcera péptica activa, sangrado gastrointestinal, tercer trimestre de embarazo.',
            ],
            [
                'active_principle' => 'Paracetamol',
                'concentration' => '500mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Tylenol',
                'requires_prescription' => false,
                'contraindications' => 'Insuficiencia hepática grave o hipersensibilidad al paracetamol.',
            ],
            [
                'active_principle' => 'Cloranfenicol',
                'concentration' => '0.5%',
                'presentation' => 'GOTAS',
                'administration_route' => 'TOPICA',
                'commercial_name' => 'Oftacol',
                'requires_prescription' => true,
                'contraindications' => 'Hipersensibilidad a la sustancia activa, antecedentes de insuficiencia medular.',
            ],
            [
                'active_principle' => 'Betametasona',
                'concentration' => '0.05%',
                'presentation' => 'CREMA',
                'administration_route' => 'TOPICA',
                'commercial_name' => 'Betnovate',
                'requires_prescription' => true,
                'contraindications' => 'Infecciones cutáneas virales primarias (herpes, varicela), tuberculosis cutánea.',
            ],
            [
                'active_principle' => 'Omeprazol',
                'concentration' => '20mg',
                'presentation' => 'CAPSULA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Losec',
                'requires_prescription' => false,
                'contraindications' => 'Hipersensibilidad a benzimidazoles, coadministración con nelfinavir.',
            ],
            [
                'active_principle' => 'Metformina',
                'concentration' => '850mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Glucophage',
                'requires_prescription' => true,
                'contraindications' => 'Cetoacidosis diabética, insuficiencia renal grave, insuficiencia cardíaca aguda.',
            ],
            [
                'active_principle' => 'Losartán',
                'concentration' => '50mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Cozaar',
                'requires_prescription' => true,
                'contraindications' => 'Embarazo, hipersensibilidad al losartán, insuficiencia hepática grave.',
            ],
            [
                'active_principle' => 'Dexametasona',
                'concentration' => '4mg/ml',
                'presentation' => 'AMPOLLA',
                'administration_route' => 'INTRAMUSCULAR',
                'commercial_name' => 'Decadron',
                'requires_prescription' => true,
                'contraindications' => 'Infecciones fúngicas sistémicas, administración de vacunas vivas.',
            ],
            [
                'active_principle' => 'Ceftriaxona',
                'concentration' => '1g',
                'presentation' => 'AMPOLLA',
                'administration_route' => 'INTRAMUSCULAR',
                'commercial_name' => 'Rocephin',
                'requires_prescription' => true,
                'contraindications' => 'Hipersensibilidad a cefalosporinas, neonatos hiperbilirrubinémicos.',
            ],
            [
                'active_principle' => 'Ranitidina',
                'concentration' => '50mg/2ml',
                'presentation' => 'AMPOLLA',
                'administration_route' => 'INTRAVENOSA',
                'commercial_name' => 'Zantac',
                'requires_prescription' => true,
                'contraindications' => 'Hipersensibilidad a la ranitidina, historial de porfiria aguda.',
            ],
            [
                'active_principle' => 'Ketorolaco',
                'concentration' => '30mg/ml',
                'presentation' => 'AMPOLLA',
                'administration_route' => 'INTRAMUSCULAR',
                'commercial_name' => 'Dolac',
                'requires_prescription' => true,
                'contraindications' => 'Úlcera péptica activa, hemorragia gastrointestinal reciente, insuficiencia renal moderada/grave.',
            ],
            [
                'active_principle' => 'Loratadina',
                'concentration' => '10mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Claritin',
                'requires_prescription' => false,
                'contraindications' => 'Hipersensibilidad o alergia al principio activo.',
            ],
            [
                'active_principle' => 'Cetirizina',
                'concentration' => '10mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Zyrtec',
                'requires_prescription' => false,
                'contraindications' => 'Insuficiencia renal terminal, hipersensibilidad a la cetirizina.',
            ],
            [
                'active_principle' => 'Diclofenaco Sódico',
                'concentration' => '75mg/3ml',
                'presentation' => 'AMPOLLA',
                'administration_route' => 'INTRAMUSCULAR',
                'commercial_name' => 'Voltaren',
                'requires_prescription' => true,
                'contraindications' => 'Úlcera gastroduodenal, asma desencadenada por AAS, insuficiencia cardíaca congestiva.',
            ],
            [
                'active_principle' => 'Diclofenaco Potásico',
                'concentration' => '50mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Cataflam',
                'requires_prescription' => true,
                'contraindications' => 'Úlcera péptica activa, insuficiencia renal o hepática grave, tercer trimestre del embarazo.',
            ],
            [
                'active_principle' => 'Atorvastatina',
                'concentration' => '20mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Lipitor',
                'requires_prescription' => true,
                'contraindications' => 'Enfermedad hepática activa, embarazo, lactancia.',
            ],
            [
                'active_principle' => 'Enalapril',
                'concentration' => '10mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Renitec',
                'requires_prescription' => true,
                'contraindications' => 'Antecedentes de angioedema relacionado con IECA, segundo y tercer trimestre del embarazo.',
            ],
            [
                'active_principle' => 'Captopril',
                'concentration' => '25mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Capoten',
                'requires_prescription' => true,
                'contraindications' => 'Antecedentes de angioedema hereditario o idiopático, estenosis bilateral de la arteria renal.',
            ],
            [
                'active_principle' => 'Amlodipina',
                'concentration' => '5mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Norvasc',
                'requires_prescription' => true,
                'contraindications' => 'Hipotensión grave, shock cardiogénico, obstrucción del flujo del ventrículo izquierdo.',
            ],
            [
                'active_principle' => 'Carvedilol',
                'concentration' => '6.25mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Coreg',
                'requires_prescription' => true,
                'contraindications' => 'Asma bronquial, EPOC, bloqueo AV de segundo o tercer grado, bradicardia grave.',
            ],
            [
                'active_principle' => 'Salbutamol',
                'concentration' => '2mg/5ml',
                'presentation' => 'JARABE',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Ventolin',
                'requires_prescription' => true,
                'contraindications' => 'Hipersensibilidad al salbutamol. Amenaza de aborto durante el primer o segundo trimestre.',
            ],
            [
                'active_principle' => 'Prednisona',
                'concentration' => '50mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Meticorten',
                'requires_prescription' => true,
                'contraindications' => 'Infecciones fúngicas sistémicas, vacunas de virus vivos atenuados.',
            ],
            [
                'active_principle' => 'Metoclopramida',
                'concentration' => '10mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Primperan',
                'requires_prescription' => true,
                'contraindications' => 'Hemorragia gastrointestinal, obstrucción mecánica o perforación, feocromocitoma.',
            ],
            [
                'active_principle' => 'Ondansetrón',
                'concentration' => '8mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Zofran',
                'requires_prescription' => true,
                'contraindications' => 'Uso concomitante con apomorfina, hipersensibilidad al ondansetrón.',
            ],
            [
                'active_principle' => 'Hioscina',
                'concentration' => '10mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Buscapina',
                'requires_prescription' => false,
                'contraindications' => 'Glaucoma de ángulo estrecho, hipertrofia prostática con retención urinaria, megacolon.',
            ],
            [
                'active_principle' => 'Levotiroxina',
                'concentration' => '100mcg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Euthyrox',
                'requires_prescription' => true,
                'contraindications' => 'Tirotoxicosis no tratada, insuficiencia adrenal no tratada, infarto agudo de miocardio.',
            ],
            [
                'active_principle' => 'Ciprofloxacina',
                'concentration' => '500mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Cipro',
                'requires_prescription' => true,
                'contraindications' => 'Hipersensibilidad a quinolonas, administración concomitante con tizanidina.',
            ],
            [
                'active_principle' => 'Azitromicina',
                'concentration' => '500mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Zithromax',
                'requires_prescription' => true,
                'contraindications' => 'Hipersensibilidad a la azitromicina, eritromicina o cualquier antibiótico macrólido.',
            ],
            [
                'active_principle' => 'Fluconazol',
                'concentration' => '150mg',
                'presentation' => 'CAPSULA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Diflucan',
                'requires_prescription' => true,
                'contraindications' => 'Coadministración con terfenadina, astemizol, cisaprida.',
            ],
            [
                'active_principle' => 'Clindamicina',
                'concentration' => '300mg',
                'presentation' => 'CAPSULA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Dalacin C',
                'requires_prescription' => true,
                'contraindications' => 'Antecedentes de colitis pseudomembranosa, hipersensibilidad a la clindamicina o lincomicina.',
            ],
            [
                'active_principle' => 'Metronidazol',
                'concentration' => '500mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Flagyl',
                'requires_prescription' => true,
                'contraindications' => 'Hipersensibilidad a derivados imidazólicos, primer trimestre del embarazo, consumo de alcohol.',
            ],
            [
                'active_principle' => 'Albendazol',
                'concentration' => '400mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Zentel',
                'requires_prescription' => true,
                'contraindications' => 'Embarazo o sospecha del mismo, lactancia, hipersensibilidad.',
            ],
            [
                'active_principle' => 'Clonazepam',
                'concentration' => '2mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Rivotril',
                'requires_prescription' => true,
                'contraindications' => 'Insuficiencia respiratoria grave, miastenia gravis, apnea del sueño, insuficiencia hepática grave.',
            ],
            [
                'active_principle' => 'Alprazolam',
                'concentration' => '0.5mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Tafil',
                'requires_prescription' => true,
                'contraindications' => 'Miastenia gravis, insuficiencia respiratoria severa, glaucoma de ángulo cerrado.',
            ],
            [
                'active_principle' => 'Sertralina',
                'concentration' => '50mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Zoloft',
                'requires_prescription' => true,
                'contraindications' => 'Uso concomitante con IMAO o pimozida.',
            ],
            [
                'active_principle' => 'Fluoxetina',
                'concentration' => '20mg',
                'presentation' => 'CAPSULA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Prozac',
                'requires_prescription' => true,
                'contraindications' => 'Uso concomitante con IMAO, hipersensibilidad a la fluoxetina.',
            ],
            [
                'active_principle' => 'Tramadol',
                'concentration' => '100mg/2ml',
                'presentation' => 'AMPOLLA',
                'administration_route' => 'INTRAVENOSA',
                'commercial_name' => 'Tramal',
                'requires_prescription' => true,
                'contraindications' => 'Intoxicación aguda por alcohol, sedantes u opioides. Uso concomitante con IMAO.',
            ],
            [
                'active_principle' => 'Meloxicam',
                'concentration' => '15mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Mobic',
                'requires_prescription' => true,
                'contraindications' => 'Úlcera péptica activa, insuficiencia cardíaca severa, insuficiencia renal severa no dializada.',
            ],
            [
                'active_principle' => 'Naproxeno',
                'concentration' => '500mg',
                'presentation' => 'TABLETA',
                'administration_route' => 'ORAL',
                'commercial_name' => 'Flanax',
                'requires_prescription' => false,
                'contraindications' => 'Hipersensibilidad al naproxeno, broncoespasmo o pólipos nasales inducidos por AAS.',
            ],
        ];

        foreach ($medications as $med) {
            $existing = Medication::where('active_principle', $med['active_principle'])
                ->where('concentration', $med['concentration'])
                ->where('presentation', $med['presentation'])
                ->first();

            if (!$existing) {
                Medication::create(array_merge($med, [
                    'uuid' => (string) Str::uuid(),
                    'is_active' => true,
                ]));
            }
        }
    }
}
